# Generated by Django 2.0.9 on 2019-02-03 00:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceConnections',
            new_name='DeviceHeartbeat',
        ),
        migrations.AlterField(
            model_name='sprinkleschedule',
            name='am_pm',
            field=models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=5),
        ),
        migrations.AlterField(
            model_name='sprinkleschedule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprinkle_scheduled', to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='sprinkleschedule',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
