# Generated by Django 2.0.9 on 2019-02-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190203_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinkleschedule',
            name='last_run',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sprinkleschedule',
            name='next_schedule',
            field=models.DateTimeField(null=True),
        ),
    ]
