# Generated by Django 2.2.2 on 2019-06-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20190317_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceheartbeat',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
