version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: pomelo_dev_nginx
    ports:
      - "8000:8000"
    volumes:
      - ../nginx:/etc/nginx/conf.d
      - ../../.collect_static:/static
    depends_on:
      - web
    networks:
      - backend
  web:
    build: ../../
    container_name: pomelo_dev_web
    command: ["./entrypoint.sh"]
    environment:
      ENVIRONMENT: production
    depends_on:
      - db
    volumes:
      - ../../.collect_static:/static
    expose:
      - "8000"
    networks:
      - backend
  db:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: dev_test
      MYSQL_DATABASE: aquas_db
      MYSQL_USER: django_aquas
      MYSQL_PASSWORD: mypassword
    container_name: pomelo_dev_db
    networks:
      - backend
networks:
  backend:

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #   restart: always
  #   ports:
  #     - 8082:80
  #   networks:
  #     - backend
  #   volumes:
  #     - /sessions
